extensions:
  - name: python
    file_extension: py
    source_lib: ./target/debug/libpy_source.so
    sink_lib: ./target/debug/libpy_sink.so
    operator_lib: ./target/debug/libpy_op.so
    config_lib_key: python-script