[package]
name = "zenoh-flow-python"
version = "0.4.0"
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = "0.16"
zenoh-flow-python-common = { path = "../zenoh-flow-python-common/" }

[features]
abi-py37 = ["pyo3/abi3-py37"]
extension-module = ["pyo3/extension-module"]
default = ["extension-module", "abi-py37"]

[lib]
name = "zenoh_flow"
crate-type = ["cdylib"]
