- file_extension: py
  libraries:
    sink: /Users/julien/dev/zenoh-flow-python/target/debug/libzenoh_flow_python_sink_wrapper.dylib
    source: /Users/julien/dev/zenoh-flow-python/target/debug/libzenoh_flow_python_source_wrapper.dylib
    operator: /Users/julien/dev/zenoh-flow-python/target/debug/libzenoh_flow_python_operator_wrapper.dylib
